# Generated by Django 4.0.4 on 2022-04-24 09:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buddlunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_privacy', models.BooleanField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('level', models.CharField(choices=[('M1', 'Master 1'), ('M2', 'Master 2'), ('PhD', 'Doctorate')], max_length=50)),
                ('study', multiselectfield.db.fields.MultiSelectField(choices=[('advanced_materials', 'Advanced Materials'), ('life_sciences', 'Life Sciences'), ('chemistry_and_interfacts', 'Chemistry and Interfacts'), ('computer_science', 'Computer Science'), ('data_and_artificial_intelligence', 'Data and Artificial Intelligence'), ('economics', 'Economics'), ('electrical_engineering', 'Electrical Engineering'), ('energy_for_climate', 'Energy for Climate'), ('mathematics', 'Mathematics'), ('mechanics', 'Mechanics'), ('physics', 'Physics'), ('quantum_science_and_technologies', 'Quantum Science and Technologies')], max_length=222)),
                ('nb_buddies', models.IntegerField()),
                ('gender', models.CharField(choices=[('unknown', "I'd rather not say"), ('male', 'Male'), ('female', 'Female'), ('other', 'Non binary / Third gender')], max_length=50)),
                ('gender_matching', models.CharField(choices=[('no_preference', "I don't have any preference."), ('same', 'I prefer to match with the same gender.')], max_length=50)),
                ('jung_personality_test', models.CharField(blank=True, choices=[('intj', 'Architect (INTJ)'), ('intp', 'Logician (INTP)'), ('entj', 'Commander (ENTJ)'), ('entp', 'Debater (ENTP)'), ('infj', 'Advocate (INFJ)'), ('infp', 'Mediator (INFP)'), ('enfj', 'Protagonist (ENFJ)'), ('enfp', 'Campaigner (ENFP)'), ('istj', 'Logistician (ISTJ)'), ('isfj', 'Defender (ISFJ)'), ('estj', 'Executive (ESTJ)'), ('esfj', 'Consul (ESFJ)'), ('istp', 'Virtuoso (ISTP)'), ('isfp', 'Adventurer (ISFP)'), ('estp', 'Entrepreneur (ESTP)'), ('esfp', 'Entertainer (ESFP)')], max_length=50)),
                ('has_matched', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_privacy', models.BooleanField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('level', models.CharField(choices=[('M1', 'Master 1'), ('M2', 'Master 2'), ('PhD', 'Doctorate')], max_length=50)),
                ('study', multiselectfield.db.fields.MultiSelectField(choices=[('advanced_materials', 'Advanced Materials'), ('life_sciences', 'Life Sciences'), ('chemistry_and_interfacts', 'Chemistry and Interfacts'), ('computer_science', 'Computer Science'), ('data_and_artificial_intelligence', 'Data and Artificial Intelligence'), ('economics', 'Economics'), ('electrical_engineering', 'Electrical Engineering'), ('energy_for_climate', 'Energy for Climate'), ('mathematics', 'Mathematics'), ('mechanics', 'Mechanics'), ('physics', 'Physics'), ('quantum_science_and_technologies', 'Quantum Science and Technologies')], max_length=222)),
                ('gender', models.CharField(choices=[('unknown', "I'd rather not say"), ('male', 'Male'), ('female', 'Female'), ('other', 'Non binary / Third gender')], max_length=50)),
                ('gender_matching', models.CharField(choices=[('no_preference', "I don't have any preference."), ('same', 'I prefer to match with the same gender.')], max_length=50)),
                ('jung_personality_test', models.CharField(blank=True, choices=[('intj', 'Architect (INTJ)'), ('intp', 'Logician (INTP)'), ('entj', 'Commander (ENTJ)'), ('entp', 'Debater (ENTP)'), ('infj', 'Advocate (INFJ)'), ('infp', 'Mediator (INFP)'), ('enfj', 'Protagonist (ENFJ)'), ('enfp', 'Campaigner (ENFP)'), ('istj', 'Logistician (ISTJ)'), ('isfj', 'Defender (ISFJ)'), ('estj', 'Executive (ESTJ)'), ('esfj', 'Consul (ESFJ)'), ('istp', 'Virtuoso (ISTP)'), ('isfp', 'Adventurer (ISFP)'), ('estp', 'Entrepreneur (ESTP)'), ('esfp', 'Entertainer (ESFP)')], max_length=50)),
                ('has_matched', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
