# Generated by Django 3.2.7 on 2021-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('programme_type', models.CharField(choices=[('m1', 'Master 1'), ('m2', 'Master 2'), ('phd', 'PhD track')], max_length=3)),
                ('programme_name', models.CharField(max_length=63)),
                ('membership_fee_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
