# Generated by Django 3.2.7 on 2022-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='programme_type',
        ),
        migrations.AddField(
            model_name='member',
            name='master_level',
            field=models.CharField(choices=[('m1', 'Master 1'), ('m2', 'Master 2')], default='m1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phd_track',
            field=models.BooleanField(default=False),
        ),
    ]
